SilverStripe\SiteConfig\SiteConfig:
  main_config:
    Title: "My Dojo Site"
    Tagline: "Serving the community through martial arts"
    DojoName: "The Dojo Training Hall"
    DojoAddress: "15 Somestreet, Somearea, SomeCity"
    ContactEmail: "support@example.com"
    FacebookLink: "https://www.facebook.com/MyDojoSite"
