name: 🚀 Deploy site to prod on push of `production` branch

on:
  push:
    branches:
      - production

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Check out latest code
        uses: actions/checkout@v4.2.0

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: 📦 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🏗️ Expose assets
        run: |
          export SS_VENDOR_METHOD=copy
          # Execute the plugin via composer
          composer vendor-expose

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: www.graydojo.org
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            .ddev/
            .github/
            vendor/
            composer.json
            composer.lock
            package.json
            yarn.lock
            tsconfig.json
            webpack.mix.js
            .eslint*
            .stylelintrc.json
            .nvmrc
            README.md
